Aqu component
SemperAvanti/semper-avanti pull request #13
Opened 2024-03-18 08:10 UTC by kq333

2024-03-18 13:36 UTC, HubertKlamann approved these changes

2024-03-18 13:52 UTC, MateuszSlezak requested changes
Drobne poprawki a tak to super !

2024-03-18 13:52 UTC, MateuszSlezak commented on src/app/components/AquComponent/Aqu.tsx
> +        {data.length ? (
W przypadku braku danych. Zawsze będziemy mieli loading... co nie jest pożądanym zachowaniem.

2024-03-18 13:52 UTC, MateuszSlezak commented on src/app/components/AquComponent/Aqu.tsx
> +              <Image src={elem.icon} alt="icon" width={24} height={24} />
warto dodac w obiekcie data alt dla kazdego obrazka i uzywac tutaj zmiennej.

2024-03-18 13:52 UTC, MateuszSlezak commented on src/app/components/AquComponent/Aqu.tsx
> +              <h5 className="aqu-section__title">{elem.title}</h5>
po h2 powinno byc h3 ;D

2024-03-18 21:25 UTC, kq333 commented on src/app/components/AquComponent/Aqu.tsx
> +        {data.length ? (
Właśnie taki jest zamysł. Tutaj tylko wisałem 'loading' bo trzeba będzie stworzyć normalny loader.

2024-03-20 06:27 UTC, Sancz0pansa approved these changes

2024-03-20 09:01 UTC, merged