Footer
SemperAvanti/semper-avanti pull request #15
Opened 2024-03-18 10:24 UTC by MateuszSlezak

2024-03-18 13:52 UTC, HubertKlamann requested changes

2024-03-18 13:52 UTC, HubertKlamann commented on src/app/components/Footer/Footer.tsx
> +          </a>
może coś takiego: const links = [
{label: 'Home', href: '#'},
itd...
]
potem mapowanie links.map((link, index) => <a key={index}></a> itd...) bardziej czytelne i łatwiejsze w zarządzaniu :)

2024-03-21 10:50 UTC, HubertKlamann approved these changes

2024-03-21 10:51 UTC, SemperAvanti approved these changes

2024-03-21 12:18 UTC, merged