Refactor/move logic from home to form
SemperAvanti/semper-avanti pull request #19
Opened 2024-03-20 18:55 UTC by kq333

2024-03-20 19:02 UTC, SemperAvanti commented on src/app/page.tsx
>  'use client';
To juz mozesz wyjebac bo nie musi to byc po stronie klienta robione

2024-03-20 19:02 UTC, SemperAvanti commented on src/app/components/FormComponent/Form.tsx
> +      document.documentElement.style.position = 'relative';
Czemu takie cos? Daj jak cywilizowany człowiek temu klase czy cos

2024-03-20 19:02 UTC, SemperAvanti commented on src/app/components/FormComponent/Form.tsx
>        }, 2000);
Czemu to jest w setTimeoucie?

2024-03-21 13:35 UTC, MateuszSlezak requested changes
Musisz zaktualizowac do maina .

2024-03-21 18:38 UTC, MateuszSlezak requested changes
nadal tego maina nie zmergowales ;D

2024-03-21 19:46 UTC, closed without merging