Menu locale fix
SemperAvanti/semper-avanti pull request #58
Opened 2024-06-05 18:37 UTC by MateuszSlezak

2024-06-05 20:40 UTC, Timi2424 reviewed
looks okey other than the comments I wrote, for the contentful part if it works it works

2024-06-05 20:40 UTC, Timi2424 commented on src/app/components/Menu/Menu.tsx
>                        <ul className="languagesList">
is this list any different than the one below? you could extract this as a component instead of repeating it twice

2024-06-05 20:40 UTC, Timi2424 commented on src/app/components/Menu/Menu.tsx
>                        <ul className="languagesList">
additionally the the logic is very redundant, is it not better to just not display the button of the language already set?

2024-06-07 10:15 UTC, danon321 requested changes

2024-06-07 10:15 UTC, danon321 commented on src/app/components/Menu/Menu.tsx
> +                        {actualLanguage !== 'English' && (
Zgadzam sie z tymonem. Pierdolnij tu jakiegos loopa bo przeciez to sa literalnie te same informacje. No i za kazdym razem jak bedziesz dodawał nowy jezyk to tez tutaj bedziesz musiał to wpisac.

2024-06-07 10:15 UTC, danon321 commented on src/app/components/Menu/Menu.tsx
> +                    {actualLanguage !== 'English' && (
Czemu my to tataj powtarzamy znowu? Zrob z tego jeden komponent bo logika jest ta sama. Wyglad mozesz zmieniac za pomocą jakiegos propsa czy cos

2024-06-07 10:15 UTC, danon321 commented on src/app/components/Menu/Menu.tsx
> +
Te całe informacje odnosnie locale to w ogole trzeba gdzies przeniesc i to tutaj importować. 
Wydaje mi sie ze moze to poleciec do pliku i18nConfig

2024-06-07 10:26 UTC, danon321 requested changes

2024-06-07 10:26 UTC, danon321 commented on src/app/components/Menu/Menu.tsx
> +  }, [route]);
Wyjeb tego całego useEffecta i bierz locale z 
import { useParams } from 'next/navigation';
const {locale} = useParams();

2024-06-10 23:24 UTC, SemperAvanti requested changes

2024-06-10 23:24 UTC, SemperAvanti commented on src/app/components/Menu/LangMenu.tsx
> +  const [activeLanguage, setActiveLanguage] = useState('English');
tutaj sie ustawia domyslny jezyk a te informacje tez mamy w i18config. Ogarnac zeby było tez z tamtego objektu location

2024-06-10 23:24 UTC, SemperAvanti commented on src/app/components/Menu/LangMenu.tsx
> +  }, [route]);
Do wyjebania i lokacje brac jak człowiek

2024-06-10 23:24 UTC, SemperAvanti commented on src/app/components/Menu/LangMenu.tsx
> +  }, [showLanguages]);
to jest do klikania poza komponent tak?

2024-06-10 23:24 UTC, SemperAvanti commented on src/i18nConfig.ts
> +  locales: ['en-US', 'pl-PL', 'es-ES'],
Jebnij tu mapa zeby z objektu locale brało te tablice bedzie wygladać cool

2024-06-11 10:49 UTC, SemperAvanti approved these changes

2024-06-11 10:49 UTC, danon321 approved these changes

2024-06-11 10:49 UTC, danon321 commented on src/app/components/Menu/Menu.tsx
> +                          <button
Zamiast `< button >` zrob z tego `<Link> ` z next.js

2024-06-11 10:51 UTC, merged