Aqu trainings about contentfull
SemperAvanti/semper-avanti pull request #59
Opened 2024-06-10 18:16 UTC by MateuszSlezak

Dodanie implementacji Contentfull do sekcji : AQU , AboutUs, Trainings (bez obrazków)

2024-06-10 19:16 UTC, SemperAvanti requested changes

2024-06-10 19:16 UTC, SemperAvanti commented on src/app/components/AquComponent/Aqu.tsx
> +                  // @ts-ignore
dodaj po prostu "as string" wygląda ładniej

2024-06-10 19:16 UTC, SemperAvanti commented on src/app/[locale]/page.tsx
> +        <TrainingPage locale={locale} />
podmien na useParams()

2024-06-10 19:16 UTC, SemperAvanti commented on src/app/components/AquComponent/Aqu.tsx
> +            <div></div>
po co to

2024-06-10 19:16 UTC, SemperAvanti commented on src/app/components/AquComponent/Aqu.tsx
> +      />
?

2024-06-10 19:16 UTC, SemperAvanti commented on src/app/components/TrainingsCard/TrainingsCard.tsx
> +  value5: string;
co to jest value12345?

2024-06-10 19:16 UTC, SemperAvanti commented on src/app/components/TrainingsCard/TrainingsCard.tsx
> +            <p className="training-card__left">{value2}</p>
moze po prostu zrób tutaj map?

2024-06-10 19:16 UTC, SemperAvanti commented on src/app/components/TrainingsPage/TrainingsPage.tsx
> +              i % 2 !== 0 ? (
o co w tym chodzi?

2024-06-10 19:16 UTC, SemperAvanti commented on src/app/components/TrainingsPage/TrainingsPage.tsx
> +                      value5={item.fields.field5Name as string}
to wyglada strasznie wrzuc to w jakiegos arraya czy object i daj jako jeden props

2024-06-10 19:16 UTC, SemperAvanti commented on src/lib/api.ts
> +  console.log(response.items);
usun

2024-06-10 19:21 UTC, MateuszSlezak commented on src/app/components/AquComponent/Aqu.tsx
> +                  // @ts-ignore
nie da rady tak tego załatwić bo dostaje zwrotke że może być null

2024-06-11 20:23 UTC, MateuszSlezak commented on src/app/components/TrainingsCard/TrainingsCard.tsx
> +  value5: string;
to sa te nazwy pol w karcie

2024-06-12 07:34 UTC, Timi2424 requested changes
Błędy ts powstają głownie przy getContent i getMultipleContent sprawdź czy contentful nie posiada wbudowanych typów które mógłbyś tu zaaplikować, Ja znalazłem np Entry, EntrySkeletonType
Te useEffekty trzymałbym w hooku i używał gdzie trzeba, bo znowu jest bardzo dużo powtarzania kodu. Poprawi to czytelność, ułatwi tobie typowanie i będzie git 

daniel mnie uświadomił, że to ma być server side, zoink

2024-06-12 07:34 UTC, Timi2424 commented on src/app/components/AquComponent/Aqu.tsx
> +  useEffect(() => {
używasz tego w paru miejscach, lepiej zrobić z tego custom hooka i dac do lib

2024-06-12 07:34 UTC, Timi2424 commented on src/app/components/AquComponent/Aqu.tsx
> +  const { locale } = useParams();
useparams ma generyka z biblioteki, możesz też użyć { locale: string }

2024-06-12 07:34 UTC, Timi2424 commented on src/app/components/AquComponent/Aqu.tsx
> +  useEffect(() => {
będziesz mógł wtedy trzymać typy w jednym miejscu, a tam gdzie użyjesz hooka nie powinien cię o nie pytać

2024-06-12 07:34 UTC, Timi2424 commented on src/app/components/AquComponent/Aqu.tsx
> +interface Card {
nie zapomniałeś o tym?

2024-06-12 07:34 UTC, Timi2424 commented on src/app/components/AquComponent/Aqu.tsx
> +      const cards = await getMultipleContent(
użyj try catcha, fajnie by było jakby nie zmieniało kontentu na null przy errorze

2024-06-12 07:34 UTC, Timi2424 commented on src/app/components/Menu/Menu.tsx
> +   const route = useRouter();
sprzątaj po sobie

2024-06-12 07:34 UTC, Timi2424 commented on src/app/components/Menu/Menu.tsx
> +
?

2024-06-12 07:34 UTC, Timi2424 commented on src/app/components/SectionAboutUs/SectionAboutUs.tsx
> +  const { locale } = useParams();
tutaj tak samo, masz generyka od paramsów

2024-06-12 07:34 UTC, Timi2424 commented on src/app/components/SectionAboutUs/SectionAboutUs.tsx
> +  useEffect(() => {
wszystkie uwagi z poprzedniej sekcji tak samo tutaj

2024-06-12 07:34 UTC, Timi2424 commented on src/app/components/SectionAboutUs/SectionAboutUs.tsx
> +      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
to nie jest dobre wyjście na errory tsa, to już lepiej w ogóle go nie używać

2024-06-12 07:34 UTC, Timi2424 commented on src/app/components/TrainingsPage/TrainingsPage.tsx
> +  useEffect(() => {
x3

2024-06-12 07:36 UTC, Timi2424 commented on src/app/components/TrainingsPage/TrainingsPage.tsx
> +interface Content {
ten typ przerzuciłbym też do api, zmienił na opcjonalne parametry, @danon321 spoko?

2024-06-21 08:49 UTC, Timi2424 approved these changes

2024-06-21 08:49 UTC, merged