add styles/variables
SemperAvanti/semper-avanti pull request #6
Opened 2024-03-11 20:59 UTC by MateuszSlezak

2024-03-12 16:26 UTC, HubertKlamann requested changes
tak dla przypomnienia zaznaczyłem kilka żeczy o których rozmawialiśmy na daily

2024-03-12 16:26 UTC, HubertKlamann commented on src/app/layout.tsx
> +import '../styles/variables.scss';
plik importujący style: 
![image](https://github.com/SemperAvanti/semper-avanti/assets/125998242/90db310f-8ddb-4241-8bd0-d5fdf17fb499)
potem wystarczy użyć jednego importu w głównym pliku

2024-03-12 16:26 UTC, HubertKlamann commented on src/app/page.tsx
> +      <section className="container">
tak jak rozmawialiśmy na daily, jeden container wystarczy

2024-03-12 16:26 UTC, HubertKlamann commented on src/styles/globalModule.scss
> +}
zaznaczam, żebyś pamiętał że to w osobnym pliku powinno być i zaimportowane do pliku index.scss

2024-03-12 16:42 UTC, MateuszSlezak commented on src/styles/globalModule.scss
> +}
all done!

2024-03-12 20:44 UTC, Sancz0pansa approved these changes

2024-03-13 11:55 UTC, HubertKlamann approved these changes
Good :D

2024-03-13 13:25 UTC, merged