buttons
SemperAvanti/semper-avanti pull request #7
Opened 2024-03-13 14:46 UTC by ogospadzipalina

![Uploading Zrzut ekranu 2024-03-13 144701.png…]()

2024-03-13 14:53 UTC, SemperAvanti commented on src/app/components/Button/button.scss
> +  width: 262px;
bez sztywnych szerokosci. Niektore buttony beda miały inny tekst w sobie. Szerokosc powinnas załatwić padingami

2024-03-13 14:53 UTC, SemperAvanti commented on src/app/components/Button/Button.tsx
> +  return <button className={buttonClass}>{name}</button>;
Powinnas jeszcze tutaj dodac ze jest disabled button jak jest 'deactivated'

2024-03-13 15:03 UTC, MateuszSlezak commented on src/app/components/Button/button.scss
> +  &:focus {
focus should have the same color like hover , u should add next class :active with background-color: $color-button-active;

2024-03-14 16:39 UTC, MateuszSlezak requested changes
te 2 male zmiany i mozna mergowac ;D

2024-03-14 16:39 UTC, MateuszSlezak commented on src/app/components/Button/button.scss
> +  &:focus {
jednak sprawdzilem ten focus i po kliknieciu focus zostaje na elemencie wiec nie moze go byc wogole.

2024-03-14 16:39 UTC, MateuszSlezak commented on src/app/components/Button/button.scss
> +  transition: background-color 0.5s ease;
0.5s za duzo wrzuc mu 0.2s

2024-03-14 21:55 UTC, merged