Form component
SemperAvanti/semper-avanti pull request #8
Opened 2024-03-14 08:11 UTC by kq333

2024-03-14 20:51 UTC, MateuszSlezak requested changes
musisz napewno zassac maina i pozamieniac media na mixiny. A co do stylowania to ciezko powiedziec bo w figmie nie ma zadnych opisow ale mam wrazenie ze tez cos jest nie tak ale to juz sie musisz designerow spytac ale to moze moja subiektywna opinia wiec dobrze zeby jeszcze ktos na to rzucil okiem ;p

2024-03-14 20:51 UTC, MateuszSlezak commented on src/app/components/FormComponent/Form.scss
> +  @media (max-width: 480px) {
w styles jest mixin do ustalania szerokosci nie masz go bo pracujesz na starym mainie ;D. przez co mamy inne breakpointy .

2024-03-18 12:24 UTC, MateuszSlezak requested changes

2024-03-18 12:24 UTC, MateuszSlezak commented on src/app/components/InputComponent/Input.scss
> +      background-color: $color-background-disabled;
nie masz zdefiniowanych tych zmiennych

2024-03-18 12:24 UTC, MateuszSlezak commented on src/app/components/InputComponent/Input.scss
> +      width: 100%;
dodaj mu klase `&:hover {
        background: $color-background-primary;
        border: 2px solid $color-red;
      }`   zeby ci ta czerwona ramka nie znikala jak na niego najezdzasz

2024-03-18 12:24 UTC, MateuszSlezak commented on src/app/components/InputComponent/Input.scss
> +    &:focus {
przenies focus ponizej hoovera zeby ci nie znikala niebieska ramka gdy na nia najezdzasz

2024-03-18 13:12 UTC, HubertKlamann approved these changes

2024-03-19 14:14 UTC, MateuszSlezak requested changes

2024-03-19 14:14 UTC, MateuszSlezak commented on src/app/components/InputComponent/Input.scss
> +        border: 2px solid $color-red !important;
usun jeszcze to important ;D

2024-03-19 14:14 UTC, MateuszSlezak commented on src/app/components/InputComponent/Input.scss
> +    &:hover {
i ten blok wrzuc przed blok ' &--isError' . albo przeklej to co ci na discorda wrzucilem no i maina bedziesz musial zaktualizowac bo juz outdated jest a tak to gitara dobra robota !!!.

2024-03-20 09:56 UTC, MateuszSlezak requested changes
Dałbyś radę jeszcze raz zmergować maina?

2024-03-20 13:43 UTC, ogospadzipalina requested changes

2024-03-20 13:43 UTC, ogospadzipalina commented on src/app/components/FormComponent/Form.tsx
> +  const [btnColor, setBtnColor] = useState('primary');
trochę źle zrobiłam, że dodałam wtedy to, co prosiłeś z buttonami a 100% na desktopie. Dla 100% na desktopie variantem powinien być secondary, a primary to jest taka, co np mamy na home. Już to zmieniłam w buttonach więc zmień też na secondary

2024-03-20 14:21 UTC, MateuszSlezak approved these changes

2024-03-20 14:21 UTC, merged